### ISSUE TITLE
Allow Sdk to be used with external wallets. 

### ISSUE THREAD

**Issue by Tailchakra** [kuyawa/davinci-sdk#1]
Correct me if I'm wrong here. Am I correct to assume this only works with access to ones private key? If so, then a feature request to accept external wallets (eg metamask, onewallet, math wallet, 1wallet)

Preferably prioritizing 1wallet or onewallet.

Other than that, this SDK is godsend.

**Comment by kuyawa** [comment]
Yes, it needs your private key, and no, it doesn't use any external wallet, this sdk is for use in terminal or scripts and you have to provide your private key directly to the sdk, there is no wallet interaction, Harmony JS lib will do the magic. Remember not to hard-code your key, better use an env var.

**Comment by Tailchakra** [comment]
Ah okay! Then I'll let this SDK walk by me. I hoped to integrate DaVinci with the dApp I'm creating. Loving the idea though!

**Comment by kuyawa** [comment]
> Ah okay! Then I'll let this SDK walk by me. I hoped to integrate DaVinci with the dApp I'm creating. Loving the idea though!

Started work on an SDK for the web so you can use it in browsers with Metamask or Harmony wallet

**Comment by kuyawa** [comment]
SDK for the web is ready, give it a try!
